---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:10
    commands:
      - npm install
      - npm test

trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: publish

steps:
  - name: test
    image: node:10
    commands:
      - npm install
      - npm test

  - name: gh-pages
    image: plugins/gh-pages
    settings:
      username: redneckz
      password:
        from_secret: github_password
      pages_directory: public/

trigger:
  event:
    - tag
