---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:10
    commands:
      - npm install
      - npm test

trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: node:10
    environment:
      NODE_ENV: production
    commands:
      - npm install
      - npm test
      - npm run build

  - name: gh-pages
    image: plugins/gh-pages
    environment:
      NODE_ENV: production
      PLUGIN_USER_NAME: Alexander Alexandrov
      PLUGIN_USER_EMAIL: aalexandrovv@gmail.com
    settings:
      username: redneckz
      password:
        from_secret: github_password
      pages_directory: build/

trigger:
  event:
    - tag
